apiVersion: batch/v1
kind: Job
metadata:
  name: my-job-test
spec:
  ttlSecondsAfterFinished: 15
  template:
    spec:
      containers:
        - name: print
          image: busybox:stable
          command: ["echo", "This is a job test!"]
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 10
