apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-1
spec:
  template:
    spec:
      containers:
      - name: print
        image: busybox:stable
        command: ["echo", "This is test job 1!"]
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 10

